version: "3"
services:
  server:
    image: booking-service
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bookingdb
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bookingdb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net: